annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-operator-crd/issues\n\
    - name: Upstream project\n  url: https://github.com/prometheus-community/helm-charts\n"
chartApiVersion: v2
chartFile: prometheus-operator-crd-22.0.1-dev.main.2026-08-06.10-03-06.ha423bde.tgz
dateCreated: '2026-08-06T10:03:34.399048Z'
digest: 2aee417e0080da91a0c0ae7c34c640ac3679beac6e360b3646f7eeecbd0a3dd8
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
