annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-operator-crd/issues\n\
    - name: Upstream project\n  url: https://github.com/prometheus-community/helm-charts\n"
chartApiVersion: v2
chartFile: prometheus-operator-crd-24.0.1-r4c02ffect20261008191250hc36201a.tgz
dateCreated: '2026-10-08T19:13:19.301901Z'
digest: cf972f1f1feb9681263ae5ecd7c44d1e50d227292a7c31ccd8b6cbb79ca20846
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
