annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-22.0.1-dev.renovate-k--stack-87-x.2026-07-09.13-37-10.hf0aecc9.tgz
dateCreated: '2026-07-09T13:37:45.177740Z'
digest: 298a6618eb746db13271397a68550fef10ee2cfcec78963168a972759703b884
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
