annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-22.0.1-dev.main.2026-07-28.09-26-20.hc3186de.tgz
dateCreated: '2026-07-28T09:26:50.381801Z'
digest: cb56afc2e85a3e0749c509df51902123d1c0a50d0c6544c980ca54c3e020dd4a
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
