annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-19.0.0-236ad17b13132376b094bf5dc7d3438bbd14191b.tgz
dateCreated: '2026-02-06T13:04:18.575435Z'
digest: f300f2905d77c660e0fa2ebab14bccdc610613fb8921aece8213ae8b90021873
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
