annotations:
  application.giantswarm.io/team: phoenix
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-blackbox-exporter-app/issues\n\
    - name: Upstream project\n  url: https://github.com/prometheus/blackbox_exporter\n"
chartApiVersion: v2
chartFile: prometheus-blackbox-exporter-0.9.1-dev.renovate-architect-10-x.2026-09-17.10-22-40.hdd53928.tgz
dateCreated: '2026-09-17T10:23:04.790273Z'
digest: 089cf63562e142f6ed1f82cfa0a5f03e2b6d71e212b75d24008ee2ab8e9f809d
home: https://github.com/giantswarm/prometheus-blackbox-exporter-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
