annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.2.0-1276f963a50eb6bb44aebe56030a952a9e84f332.tgz
dateCreated: '2026-03-27T20:26:52.778525Z'
digest: ce23cd17d95ffe8cf095f4788d1166f11f2ce41328d325238e2f989bd1ca11f6
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
