annotations:
  application.giantswarm.io/team: phoenix
chartApiVersion: v2
chartFile: prometheus-blackbox-exporter-0.5.1.tgz
dateCreated: '2026-03-11T13:55:45.783048Z'
digest: d7e3cf3b8cf9fb995d04ae58726767049d16d8ea5c4c65bcd690f1375e9aaa62
home: https://github.com/giantswarm/prometheus-blackbox-exporter-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
