annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-21.0.1-dev.main.2026-06-19.05-36-46.h977c234.tgz
dateCreated: '2026-06-19T05:37:21.043925Z'
digest: 4c4c88d633b6435fc782db4d8419b7b5808483ac066f1efe2189c0b1bbf949f2
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
