annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.2.0-e76e5655e10afd9d2cea6410076f86d287c3b958.tgz
dateCreated: '2026-04-27T09:59:30.942942Z'
digest: c61eefb8c33efe21df7251ed39a15091c5a6a080f3c131988a3af371c3a28b9b
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
