annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-21.0.1-dev.renovate-a--heckout-7-x.2026-06-18.17-46-07.h9accff1.tgz
dateCreated: '2026-06-18T17:46:43.441772Z'
digest: 05eae50140b5c659430e5be931479a93123543f1b2a4f506a4c708ab36ba5333
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
