annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-20.0.0-c0b3688c2f2c04ebfef8506c7f94b2bc60065604.tgz
dateCreated: '2026-05-09T14:49:14.225473Z'
digest: 4e00123b011dd2a8d8dfa798762d953245c7228fe17bdd322fb747515ebb2147
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
