annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-19.0.0-2026ba79de02db6e05c4e5b6f004b6c1c84057a9.tgz
dateCreated: '2026-02-12T15:32:46.664032Z'
digest: 1969d865c2770745f29c654c652a63bf0297bc60aebf73aaf5e0ed1c3b8c1502
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
