annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.1-3c658dc32b0d57a920e886c9fe5ff4be03917ace.tgz
dateCreated: '2026-02-10T04:53:20.336018Z'
digest: 60b889329d101bfdd9576e4f3d75e746bd189759619585fe23c899a773383152
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
