annotations:
  application.giantswarm.io/team: phoenix
chartApiVersion: v2
chartFile: prometheus-blackbox-exporter-0.8.1-dev.main-release-v0-9-0.2026-07-27.08-35-05.h6b07e8e.tgz
dateCreated: '2026-07-27T08:35:22.404605Z'
digest: f56a3dc3e986f822eb7e41694572474adda524f50a7c961719c1d718a4c6ba6f
home: https://github.com/giantswarm/prometheus-blackbox-exporter-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
