annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-22.0.1-dev.teams-alignment-branch.2026-07-11.12-36-07.h36e8f2d.tgz
dateCreated: '2026-07-11T12:36:32.621317Z'
digest: 772e022c5175594df2522270cddd62c7490a33ee0bdedaedf4d834ef16f6bfd3
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
