annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-21.0.1-dev.main.2026-06-09.18-13-42.h5e25726.tgz
dateCreated: '2026-06-09T18:14:08.770812Z'
digest: fe05102ad84cf40f43939c5856e1d38a18981bdb0b0709e94f943981f78335e2
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
