annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-22.0.1-dev.renovate-k--stack-88-x.2026-08-18.17-15-18.h4a27605.tgz
dateCreated: '2026-08-18T17:15:55.851731Z'
digest: d8488bd433ea28cedb38c5290805f3f0dd24900456d9606b942143bcfc2eb5d4
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
