annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.2.0-105706c2c8e82796db7a5f67a70a778725602747.tgz
dateCreated: '2026-05-07T21:51:33.603107Z'
digest: 9d68132705d229394a4d7245bc9bde63ce4b5232acfc1708dc0db6fed73d4e24
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
