annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/prometheus-operator-app-0.6.0-dbb6746610a992def63e1234ddf1575ff7dab3dd.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/prometheus-operator-app-0.6.0-dbb6746610a992def63e1234ddf1575ff7dab3dd.tgz-meta/README.md
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/prometheus-operator-app-0.6.0-dbb6746610a992def63e1234ddf1575ff7dab3dd.tgz-meta/values.schema.json
  artifacthub.io/links: "- name: Chart Source\n  url: https://github.com/prometheus-community/helm-charts\n\
    - name: Upstream Project\n  url: https://github.com/prometheus-operator/kube-prometheus\n"
  artifacthub.io/operator: 'true'
chartApiVersion: v2
chartFile: prometheus-operator-app-0.6.0-dbb6746610a992def63e1234ddf1575ff7dab3dd.tgz
dateCreated: '2021-02-23T13:49:52+00:00'
digest: 67cf0a25644361337b8f62e09627ca6640b3ec0bf95bf5c88400a852c31aeb2d
