annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-21.0.1-dev.renovate-k--stack-85-x.2026-06-12.07-06-16.ha84263e.tgz
dateCreated: '2026-06-12T07:06:49.950039Z'
digest: ea6ef80946c97e0a46658020f68ad523a8c393bcd8dde7bbd4b4ecb2d3e68ae4
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
