annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-21.0.1-dev.renovate-p--r-crds-30-x.2026-06-22.22-36-06.hfb96943.tgz
dateCreated: '2026-06-22T22:36:44.867867Z'
digest: c0fd3b82c8e130bece6ddcc4e6529606d340742b85dae3f5d515179745ccc2f7
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
