annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-21.0.1-dev.main-release-major.2026-06-29.12-25-10.h9dd3146.tgz
dateCreated: '2026-06-29T12:25:47.891225Z'
digest: e8d447035cce8d9bc3895db97fc6d9d7e6d4f7040a9c9dbd1d44de8d4bbdcf17
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
