annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-operator-crd/issues\n\
    - name: Upstream project\n  url: https://github.com/prometheus-community/helm-charts\n"
chartApiVersion: v2
chartFile: prometheus-operator-crd-24.0.1-rbf28cd64t20261008190326h736f7f7.tgz
dateCreated: '2026-10-08T19:03:56.565585Z'
digest: 566aaf0b59f6ba2e60a5ace50b14190d9bd07bd1bb894d2f0e1aec8674ba6fcb
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
