annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-21.0.1.tgz
dateCreated: '2026-06-25T07:55:07.141414Z'
digest: 1d0db5e85306e10a6e235d3f3134e8fa04dcb8c03f596255b97922c0d4d9e084
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
