annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.0.0-ea742ac0f059441ac09eb788b93732e392f0707f.tgz
dateCreated: '2026-03-03T17:12:03.434342Z'
digest: 6f9d225a01270f75bffc54073866d7b89785aba497909df5e4af8ab40588a741
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
