annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.2-12a5741a256d82b86912edf2d7c6633289e21631.tgz
dateCreated: '2026-02-12T14:32:13.997260Z'
digest: 9c1f750fb4d14578cbfa54d3129f440c2e6f7b5912b0b018355702496fec06f0
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
