annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-20.2.0-80146a62be7ff1dc565159bb88ddc84301597365.tgz
dateCreated: '2026-03-27T01:01:47.901622Z'
digest: fc3d685d12ab306ae020494b5117866fe94bdc328d994321df4d75d9aaac3f55
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
