annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-21.0.1-dev.main.2026-06-21.09-57-04.h33f89f2.tgz
dateCreated: '2026-06-21T09:57:48.003584Z'
digest: 52aa95389e711f1e8abc4ad180a5fafbaafc7aef6668d3f93de05d0d9548684e
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
